#!/bin/sh

hook_dir="$( cd "$( dirname "$0" )" && pwd )"
app="$( basename "$( dirname "$hook_dir" )" )"
repo_dir=/mnt/node/repo/$app

echo 'Starting update'
pm2 stop $app

echo 'Copying files'
GIT_WORK_TREE=$repo_dir git checkout -f master

echo 'Installing dependencies'
cd $repo_dir
rm -rf node_modules
npm install --production

pm2 restart $app
echo 'Update completed'
